const SOURCES = {
  homepage: "https://www.bocra.org.bw/",
  licensing: "https://www.bocra.org.bw/licensing",
  complaints: "https://www.bocra.org.bw/complaints",
  fileComplaint: "https://www.bocra.org.bw/form/file-complaint-form",
  verify: "https://customerportal.bocra.org.bw/OnlineLicenseVerification/verify/",
  typeApproval: "https://typeapproval.bocra.org.bw/",
  contact: "https://www.bocra.org.bw/bocra-contact-details",
  news: "https://www.bocra.org.bw/news-events",
  profile: "https://www.bocra.org.bw/profile",
};

export const INTENTS = [
  {
    id: "complaint",
    topic: "complaint",
    keywords: [
      "complaint",
      "report",
      "issue",
      "problem",
      "escalate",
      "overcharged",
      "billing dispute",
      "network issue",
      "poor service",
      "dropped calls",
      "slow internet",
      "no service",
      "tletlebo",
      "ngongorego",
      "mathata",
    ],
    response:
      "I can guide you on filing a complaint. I can take you to the complaints page or help you structure the details here.",
    action: { type: "navigate", label: "Complaints Page", href: "/complaints" },
    sources: [SOURCES.complaints, SOURCES.fileComplaint],
  },
  {
    id: "licensing_status",
    topic: "licensing",
    keywords: [
      "licence status",
      "license status",
      "check licence",
      "check license",
      "status",
      "track",
      "progress",
      "update",
      "verify licence",
      "verify license",
    ],
    response:
      "You can verify licences from the Verify Licence page. If you share the application reference, I can tell you what to prepare.",
    action: { type: "navigate", label: "Verify Licence", href: "/verify" },
    sources: [SOURCES.verify],
  },
  {
    id: "licensing_apply",
    topic: "licensing",
    keywords: [
      "apply for licence",
      "apply for license",
      "licensing apply",
      "licence",
      "license",
      "licensing",
      "permit",
      "register",
    ],
    response:
      "To apply for a licence, you will need your business details, service type, and supporting documents. I can walk you through the steps.",
    action: { type: "navigate", label: "Licensing Page", href: "/licensing" },
    sources: [SOURCES.licensing],
  },
  {
    id: "type_approval",
    topic: "type_approval",
    keywords: ["type approval", "device approval", "equipment approval"],
    response:
      "Type approval covers device compliance. I can outline the required documents and testing information.",
    action: { type: "navigate", label: "Documents", href: "/documents" },
    sources: [SOURCES.typeApproval],
  },
  {
    id: "consumer",
    topic: "consumer",
    keywords: [
      "consumer",
      "rights",
      "quality of service",
      "qos",
      "billing",
      "unfair charges",
      "misleading",
      "contract dispute",
      "ditshwanelo",
      "tshegetso",
      "dira tshiamolao",
    ],
    response:
      "I can help with consumer rights, QoS issues, and billing disputes. Tell me what happened and I will guide you.",
    action: { type: "navigate", label: "Quality of Service", href: "/qos" },
    sources: [SOURCES.complaints],
  },
  {
    id: "services",
    topic: "services",
    keywords: [
      "telecommunications",
      "telecom",
      "broadcasting",
      "postal services",
      "postal",
      "internet services",
    ],
    response:
      "BOCRA regulates telecoms, broadcasting, and postal services. Which service area do you need help with?",
    action: { type: "navigate", label: "Licensing Page", href: "/licensing" },
    sources: [SOURCES.homepage],
  },
  {
    id: "news",
    topic: "news",
    keywords: ["news", "events", "updates", "press"],
    response:
      "You can view BOCRA news and events for the latest updates.",
    action: { type: "navigate", label: "News & Events", href: "/news" },
    sources: [SOURCES.news],
  },
  {
    id: "contact",
    topic: "contact",
    keywords: ["contact", "call", "email", "office", "address", "hours"],
    response:
      "You can reach BOCRA by phone at +267 3957755 or email info@bocra.org.bw. I can also open the contact page.",
    action: { type: "navigate", label: "Contact", href: "/contact" },
    sources: [SOURCES.contact, SOURCES.homepage],
  },
  {
    id: "about",
    topic: "about",
    keywords: [
      "about bocra",
      "what is bocra",
      "what does bocra do",
      "bocra profile",
      "who is bocra",
    ],
    response:
      "I can take you to the About page with the official overview.",
    action: { type: "navigate", label: "About BOCRA", href: "/about" },
    sources: [SOURCES.profile],
  },
  {
    id: "sim_registration",
    topic: "sim",
    keywords: [
      "sim registration",
      "register sim",
      "sim card",
      "activate sim",
      "sim",
      "ngodisa sim",
      "ngodisa sim card",
      "sim card ya me",
    ],
    response:
      "SIM registration requires valid identification and completion through your service provider. I can guide you on the typical steps.",
    action: { type: "navigate", label: "Documents", href: "/documents" },
    sources: [SOURCES.homepage],
  },
  {
    id: "scam_reporting",
    topic: "scam",
    keywords: [
      "scam",
      "fraud",
      "phishing",
      "sim swap",
      "spam",
      "suspicious message",
      "tsietso",
      "tsietso ya sim",
      "tsietso ka sms",
    ],
    response:
      "If you suspect a scam, document the details and report it promptly. I can guide you through next steps.",
    action: { type: "navigate", label: "Complaints Page", href: "/complaints" },
    sources: [SOURCES.complaints],
  },
];

export const QUICK_ACTIONS = [
  "File a complaint",
  "Check licence status",
  "Apply for licence",
  "Services overview",
  "Find my licence",
  "Type approval",
  "Contact BOCRA",
  "About BOCRA",
  "SIM registration",
  "Report a scam",
];
